version: '3'
services:
  app: # コンテナの名前
    build: # イメージ(コンテナのテンプレ)を作るためのDockerfileがある場所
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: chatapp
    env_file:
      - docker-compose.env
    ports: # 外部公開ポート番号 : コンテナのポート番号
      - '80:8080'
    depends_on: # 対象のコンテナとリンク
      - mysql
    volumes: # マウント。コンテナのデータと、手元のデータが同期する。自動生成
      - .:/go/src/chatapp:cached # 手元のパス : コンテナのパス : キャッシュオプション
      - .:/go/src/hot_reload_docker:cached

  mysql:
    image: mysql:5.7 # コンテナを作るためのイメージ
    container_name: chatapp-mysql
    env_file:
      - docker-compose.env
    hostname: mysql
    ports:
      - '3306:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    volumes:
      - ./docker/mysql/conf.d/mysql.conf:/etc/mysql/conf.d/my.cnf:cached
      - ./logging/mysql:/var/log/mysql:cached
      - ./docker/mysql/data:/var/lib/mysql:cached
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:cached